development:
  adapter: postgresql
  encoding: unicode
  database: myflix_development
  pool: 5
  username: jason
  password: 123qweMorpheus

test:
  adapter: postgresql
  encoding: unicode
  database: myflix_test
  pool: 5
  username: jason
  password: 123qweMorpheus
